### ISSUE TITLE
should OpenRTM software be installed following ROS-compatible directory layout?

### ISSUE THREAD

**Issue by k-okada** [start-jsk/openrtm_aist_core#1]
I am trying to download and compile `openrtm_core` in the `build` directory not `src` directory suggested at https://github.com/start-jsk/rtmros_common/issues/309, and come to this question.

As discussed in https://github.com/k-okada/rtshell_core/commit/97f81bc2b3bd1e9ba807421cabfeabce3be02590, ROS recommend to use ROS-local directory for bin and libs, however this needs very complex cmake file, ros-hydro-opencv2, ros-hydro-moveit-core did not seem to follow this convention. Of course ROS directory structure is very useful, especially if we'd like to use them with `roslaunch`.

Current directory structure is described in https://github.com/start-jsk/rtmros_common/issues/186

**Comment by k-okada** [comment]
I have question when we'd like to download and install under build/, not to pollute src/ directory, 
when we source devel/setup.sh will set
PATH -> devel/bin
ROS_PACKAGE_PATH -> src
PYTHONPATH -> devel/lib/python2.7

this means that we we'd like to invoke some script using`rosrun <package> <filename>`, the `<filename>` must be located under `src/<package>` directory, and this will pollute src directory.
If we're ok to pollute under ROS-global directory, installling `<filename>` under devel/bin, then it works ok.

So, it seems we have to choose pollute src directory(@garaemon)  or ROS-global directory(@130s).

**Comment by 130s** [comment]
My 2 cents;

I thought about why we haven't been scolded by ROS team about installing into `ROS global bin`, and that might be because it only happens when the users choose to install our packages. That said, installing into ROS bin might be permissible and that may be why there's no strict instruction not to do so.

Another idea, which may have already been thought about by someone, is that exporting the location of necessary scripts (eg. `rtls`) into `PATH` by calling:

```
$ source `rospack find openrtm_tools`/scripts/rtshell-setup.sh
```

This could make everyone happy if achievable.

And I'm afraid I just don't understand the following reasoning.

```
this means that we we'd like to invoke some script using rosrun <package> <filename>, the <filename> must be located under src/<package> directory, and this will pollute src directory.
If we're ok to pollute under ROS-global directory, installling <filename> under devel/bin, then it works ok.
```

**Comment by garaemon** [comment]
The problem of pollution of src directory is, as you know, we cannot **reset** environment by removing devel, install and build directories.

In order to satisfy this resetting, we need to:
1. use `catkin_make install` and `source install/setup.bash` always.
2. use `source devel/setup.bash` in order to execute `roscd <package>`.

But it's inconvenient and inefficient.

And, this pollution problem is critical on **generating launch files** rather than downloading external source code.

For example, let's assume we'd like to generate a launch file during catkin_make and it includes `$(find package)` in order to include another generated launch file.

**Comment by garaemon** [comment]
> In order to satisfy this resetting, we need to:
> 1. use `catkin_make install` and `source install/setup.bash` always.
> 2. use `source devel/setup.bash` in order to execute `roscd <package>`.

I didn't make myself clear.

I'm thinking about that **generating launch files** case.

If we cannot pollute src directory, we need to locate those generated files into devel or build direcotry.
and those directory is not accessible via rospack.

So, we need to locate those generated files under src directory or install directory by `catkin_make intall`.

**Comment by k-okada** [comment]
> If we cannot pollute src directory, we need to locate those generated files into devel or build direcotry.
> and those directory is not accessible via rospack.
> 
> So, we need to locate those generated files under src directory or install directory by catkin_make intall.

that's the problem, not only for generating launch files, but also we have scripts files that would be called via rosrun. If we'd like to put rtls under install/lib/openrtm_aist_pyton/bin, then we put rtls under src/...../openrtm_aist_python/bin, not devel/lib/openrtm_aist_python/bin on deve/setup.bash environment. Becaouse devel derectory is not accessiable via rospack.

**Comment by k-okada** [comment]
back to original question again: should OpenRTM software be installed following ROS-compatible directory layout?

For example, ros-rosdistro-pencv2 did not follows at all.

**Comment by 130s** [comment]
Because it looks like so many changes have happened while I've been away from building `openrtm_aist` and its child packages, I think I only have a few things to say that will sound straight forward. Apologies in advance for that.
- What about this comment from Dirk? https://github.com/start-jsk/rtmros_common/issues/346#issuecomment-36557038

Even though the packages we are working on are not build/run dependent on ROS, they are packaged with `catkin` (ie. use `package.xml`). So we have a reason to follow the (recommended) rule.
- `Opencv2` and `moveit_core` might have been changed to follow the rule?

```
$ find /opt/ros/hydro -iname 'moveit_core*'
/opt/ros/hydro/lib/pkgconfig/moveit_core.pc
/opt/ros/hydro/share/moveit_core
/opt/ros/hydro/share/moveit_core/cmake/moveit_coreConfig-version.cmake
/opt/ros/hydro/share/moveit_core/cmake/moveit_coreConfig.cmake
$ find /opt/ros/hydro -iname 'opencv2*'
/opt/ros/hydro/lib/pkgconfig/opencv2.pc
/opt/ros/hydro/share/opencv2
/opt/ros/hydro/include/opencv2
$ dpkg -p ros-hydro-opencv2 |grep Ver
Version: 2.4.6-3raring-20140303-2326-+0000
```

---

I think the specific questions of how to achieve XX (eg. generating launch files w/o messing up source folders) can be asked at answers.ros.org or `ros-sig-buildsystem@googlegroups.com`.

**Comment by k-okada** [comment]
opencv and moveit installs it's example binary code and share files under global bin directory. That makes everything very simple.

```
$ find /opt/ros/hydro/ | grep bin/opencv
/opt/ros/hydro/bin/opencv_haartraining
/opt/ros/hydro/bin/opencv_performance
/opt/ros/hydro/bin/opencv_createsamples
/opt/ros/hydro/bin/opencv_traincascade
$ find /opt/ros/hydro/ | grep bin/moveit_
/opt/ros/hydro/bin/moveit_commander_cmdline.py
/opt/ros/hydro/bin/moveit_version
$ ls /opt/ros/hydro/share/OpenCV/
OpenCVConfig-version.cmake  OpenCVConfig.cmake  haarcascades  lbpcascades
```

For example, if we have non-ROS source code that `make install` create 

```
./bin/XX.exe
./lib/XX.so
./include/XX.h
./share/XX.conf
```

ROS-style layout requires

```
src/XX/share/XX.conf ( or devel/share/XX/share/XX.conf)
devel/lib/XX/XX.exe
devel/lib/XX.so
devel/include.h
```

then if you install, the directory goes to

```
install/share/XX/share/XX.conf
install/lib/XX/XX.exe
install/lib/XX.so
install/include.h
```

Problem  on following ROS layout is:
- if you want to find share files from `rospack find XX`/share/XX.conf or `$(find XX)/share/XX.conf in launch files, you have to put share files under source directory that will violate recommendation of not put files under source directory. if you put share directory under devel/share/XX/share, you can't find them via rospack command.
- some program assumes that ./bin ./lib ,/include are put into same directory, for example: ROS-layout reques ${XX_PREFIX}/lib/XX/XX.exe and ${XX_PREFIX}/lib/XX.so

```
- set(OPENRTM_CONFIG_EXECUTABLE ${OPENRTM_DIR}/bin/rtm-config)
- set(OPENRTM_IDL_DIR ${OPENRTM_DIR}/include/openrtm-1.1/rtm/idl)
[1] https://code.google.com/p/hrpsys-base/source/browse/trunk/cmake_modules/FindOpenRTM.cmake#10
[2] https://code.google.com/p/hrpsys-base/source/browse/trunk/cmake_modules/FindOpenRTM.cmake#42
```
- pkg-config should deal with this, but since three layout (original, devel, install) difference requires complex sed script everytime we copy the XX.pc files (https://github.com/start-jsk/hrpsys/blob/master/catkin.cmake#L147, and https://github.com/start-jsk/hrpsys/blob/master/catkin.cmake#L223
