### ISSUE TITLE
Build failing on Arch Linux

### ISSUE THREAD

**Issue by bchretien** [start-jsk/openrtm_aist_core#25]
Hi!

I am maintaining ROS Hydro packages for Arch Linux , and I am currently packaging `openrtm` packages. I noticed that there are some errors in `openrtm_aist_python` related to Debian-specific functions that will not work on Arch Linux (and probably Fedora, cc @cottsay):

``` make
installed: $(SOURCE_DIR)/unpacked
    cd $(SOURCE_DIR) && python ./setup.py build && python ./setup.py install --prefix=$(INSTALL_DIR) --install-scripts $(INSTALL_SCRIPTS_DIR) --install-layout=deb 
    touch installed
```

First, the `--install-layout=deb` is specific to Debian. Second, note that you are using the system's default `python`, which is still `python2` on Ubuntu < 14.04, but `python3` on Arch Linux and possibly Ubuntu 14.04. This is a recurrent problem when packaging for Arch (forcing the use of `python2`), but this will also concern the next Ubuntu releases AFAIK.

I will patch things when packaging for Arch, and I will try to see if there is a clean way to make things go smoothly for Debian-based and non-Debian distributions.

**Comment by bchretien** [comment]
Example of a quick "Arch-only" patch: https://github.com/bchretien/openrtm_aist_core/commit/5d599233537510c1b14f7da8e4a1f82714c39388 (i.e. the patch currently applied when packaging `openrtm_aist_python` on Arch)

**Comment by k-okada** [comment]
Great!!!

As for `--install-layout=deb`, I'm not sure if this is the good solution. At this moment, we need them to force install python packages under $ROS_ROOT/lib/python2.7/dist-packages, so that $PYTHONPATH is able to find them.

previously, we used <export> tag in manifest.xml but does not work on catkin environment.
https://github.com/start-jsk/openrtm_aist_core/blob/master/openrtm_aist_python/manifest.xml

If there are way to add site-packages/OpenRTM_aist to PYTHONPATH, that's would be better.

Feel free to create Pull Request, so that we can check on the travis testing server.

**Comment by bchretien** [comment]
The same issue arose in catkin packages. They added `SETUPTOOLS_DEB_LAYOUT` to catkin to solve this (cf. https://github.com/ros/catkin/blob/indigo-devel/cmake/python.cmake#L19). I guess one of the possible solutions would be to use CMake rather than a Makefile, and use the value given to the higher-level `CMakeLists.txt`.

**Comment by k-okada** [comment]
@bchretien Ok, I created fixes to here (https://github.com/start-jsk/openrtm_aist_core/pull/31) , please check if this works for you.

**Comment by cottsay** [comment]
@k-okada and @bchretien, I can confirm that this IS a problem on Fedora and that (https://github.com/start-jsk/openrtm_aist_core/pull/31) fixes it. Thank you!
